platform :ios,9.0
inhibit_all_warnings!
use_frameworks!

def pods
    pod 'SnapKit'
    pod 'DrawerController'
    pod 'KVOController'
    pod 'MJRefresh'
    pod "SwiftSoup"
    pod 'SDWebImage', '~> 4.0'
    pod 'YYText'
    pod 'Alamofire', '~> 4.5'
    pod 'Ji'
    pod 'Kingfisher'
    pod "MWPhotoBrowser", :podspec =>'https://raw.githubusercontent.com/moinku07/MWPhotoBrowser/master/MWPhotoBrowser.podspec'
    pod 'Toast-Swift', '~> 3.0.1'
    pod 'WXImageCompress', '~> 0.1.1'
    pod 'LeanCloud'
    pod 'SQLite.swift', '~> 0.11.4'
end

target 'guanggoo-iOS' do
    pods
end
