platform :ios,9.0
inhibit_all_warnings!
use_frameworks!

def pods
    pod 'SnapKit'
    pod 'DrawerController'
    pod 'KVOController'
    pod 'MJRefresh'
    pod "SwiftSoup"
    pod 'SDWebImage'
    pod 'YYText'
    pod 'Alamofire', '~> 4.5'
    pod 'Ji'
    pod 'Kingfisher'
    pod "MWPhotoBrowser"
    pod 'Toast-Swift', '~> 3.0.1'
    pod 'WXImageCompress', '~> 0.1.1'
    pod 'SQLite.swift', '~> 0.11.4'
    pod 'CYLTabBarController', '~> 1.17.4'
    pod 'IQKeyboardManagerSwift', '5.0.0'
end

target 'guanggoo-iOS' do
    pods
end
