platform :ios,9.0
inhibit_all_warnings!
use_frameworks!

def pods
    pod 'SnapKit'
    pod 'DrawerController'
    pod 'KVOController'
    pod 'MJRefresh'
    pod "SwiftSoup"
    pod 'SDWebImage', '~> 4.0'
    pod 'YYText'
end

target 'guanggoo-iOS' do
    pods
end